name: Build and publish Docker images

on:
    workflow_dispatch:

env:
    DOCKERHUB_REPO: grishkaa/smithereen

jobs:
    build_and_push:
        strategy:
            matrix:
                platform:
                    - name: ubuntu-latest
                      arch: amd64
                    - name: ubuntu-24.04-arm
                      arch: arm64
        runs-on: ${{ matrix.platform.name }}
        steps:
            - name: Test
              run: |
                uname -a
                echo "${{ matrix.platform.arch }}"