name: Build and publish Docker images

on:
    workflow_dispatch:

env:
    DOCKERHUB_REPO: grishkaa/smithereen

jobs:
    build_and_push:
        strategy:
            matrix:
                platform: [ubuntu-latest, ubuntu-24.04-arm]
        runs-on: ${{ matrix.platform }}
        steps:
            - name: Test
              run: uname -a