name: Build and publish Docker images

on:
    workflow_dispatch:

jobs:
    build_and_push:
        strategy:
            matrix:
                platform:
                    - arch: amd64
                      runner: ubuntu-latest
                    - arch: arm64
                      runner: ubuntu-24.04-arm
        runs-on: ${{ matrix.platform.runner }}
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ vars.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  push: true
                  tags: "${{ vars.DOCKERHUB_REPO }}:latest-${{ matrix.platform.arch }}"

    merge:
        runs-on: ubuntu-latest
        needs:
            - build_and_push
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ vars.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Do the manifest thing
              run: |
                  docker manifest create ${{ vars.DOCKERHUB_REPO }}:latest --amend ${{ vars.DOCKERHUB_REPO }}:latest-amd64 --amend ${{ vars.DOCKERHUB_REPO }}:latest-arm64
                  docker manifest push ${{ vars.DOCKERHUB_REPO}}:latest